item1:
  material: STONE
  amount: 1
  data: 0
  display_name: '&8BauBence'
  lore:
    - '&aLore 1'
    - '&2Lore 2'
  custom_model_data: 0
  # https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/enchantments/Enchantment.html
  enchantments:
    - enchantment;level
  # https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/inventory/ItemFlag.html
  item_flags:
    - HIDE_ENCHANTS
  unbreakable: false
  hide_unbreakable: false
  skull_owner: kbalu
  base64: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYzA4MjU4OTgwMmIxZGUyMGZjZTdiOWNkMTIzMDM3MGZiZjM5ZWM3NTU5NDI0ZTQxNzY1YTgwODU2Zjg0ZDhkYiJ9fX0=
  # https://hub.spigotmc.org/javadocs/spigot/org/bukkit/block/banner/PatternType.html
  # https://hub.spigotmc.org/javadocs/spigot/org/bukkit/DyeColor.html
  banner_meta:
  # - red;gradient
  # - blue;gra
    - <dyecolor>;<patterntype>
    - <dyecolor>;<patterntype>
  # https://hub.spigotmc.org/javadocs/spigot/org/bukkit/DyeColor.html # Default colors
  # Hex example: leather_armor_color: '#FF00FF'
  leather_armor_color: RED